Implementation of HTML & CSS Linters
rskinnerc/hello-microverse pull request #1
Opened 2022-03-15 22:21 UTC by rskinnerc

- Install and configure linters (Webhint / Stylelint) locally.
- Create a basic HTML file and link a styles.css file.
- Update the .gitignore file accordingly to ignore unnecessary files
- Add a README.md file describing the project

2022-03-15 22:58 UTC, AmaduKamara requested changes
# Hi @rskinnerc, 

Good job so far!

![SoCloseKeeganMichaelKeyGIF (2)](https://user-images.githubusercontent.com/50941074/158485301-fb05eae5-5e14-4997-8228-25af652f671d.gif)

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Linters checks passed
✔️ Good commit messages
✔️ Used correct Gitflow

## Required Changes ♻️

- [x] Please add descriptive messages to your Pull Request (👍 plus the highlights you did)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-03-15 22:58 UTC, AmaduKamara commented on README.md
> +- etc
Good job on your README file. You've implemented most part of the README file. It would be nice you add the License as the final header description so everything will match this [README Template](https://github.com/microverseinc/readme-template/blob/master/README.md).

2022-03-15 22:58 UTC, AmaduKamara commented on .gitignore
> +test.md
Great job adding test.md to your `.gitignore` file. Please remove the `.hintrc` and `.stylelintrc.json` from the `.gitignore`. These files should not be inside of that file. Please remove them there 👍

2022-03-16 02:47 UTC, rskinnerc commented
Hello @AmaduKamara 

Thank you for your review and feedback. Regarding the required change that I must submit

> Please add descriptive messages to your Pull Request

I'm not pretty sure, how should it be... Should I add for example:
- Add index.html file
- Add styles.css file

etc.

Thank you in advance for your work

2022-03-16 06:09 UTC, AmaduKamara commented
Hey @rskinnerc, Please check out this article about [Writing A Great Pull Request Description](https://www.pullrequest.com/blog/writing-a-great-pull-request-description/). 
You're doing great so far on your project.

2022-03-16 13:38 UTC, BenMukebo approved these changes
Hi @rskinnerc, 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-16 13:49 UTC, merged